# Build NuttX for BL602 on commit

name: BL602 Commit

on:

  # Run on every commit
  push:
    branches: [ master ]

  # Run on every pull request
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Install Build Tools
      run:  |
        sudo apt -y install \
        bison flex gettext texinfo libncurses5-dev libncursesw5-dev \
        gperf automake libtool pkg-config build-essential gperf genromfs \
        libgmp-dev libmpc-dev libmpfr-dev libisl-dev binutils-dev libelf-dev \
        libexpat-dev gcc-multilib g++-multilib picocom u-boot-tools util-linux \
        kconfig-frontends \
        wget

    - name: Install Toolchain
      run:  |
        wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14.tar.gz
        tar -xvf riscv64-unknown-elf-gcc*.tar.gz

    - name: Checkout Source Files
      run:  |
        mkdir nuttx
        cd nuttx
        git clone --recursive https://github.com/lupyuen/incubator-nuttx nuttx
        git clone --recursive https://github.com/lupyuen/incubator-nuttx-apps apps
          
    - name: Build
      run: |
        # Add toolchain to PATH
        export PATH=$PATH:$PWD/riscv64-unknown-elf-gcc-8.3.0-2019.08.0-x86_64-linux-ubuntu14/bin
        cd nuttx/nuttx
        
        # Configure the build
        ./tools/configure.sh bl602evb:nsh

        # Update the build config
        kconfig-tweak --enable CONFIG_DEBUG_ERROR
        kconfig-tweak --enable CONFIG_DEBUG_WARN
        kconfig-tweak --enable CONFIG_DEBUG_INFO
        kconfig-tweak --enable CONFIG_DEBUG_ASSERTIONS

        kconfig-tweak --enable CONFIG_DEBUG_GPIO
        kconfig-tweak --enable CONFIG_DEBUG_GPIO_ERROR
        kconfig-tweak --enable CONFIG_DEBUG_GPIO_WARN
        kconfig-tweak --enable CONFIG_DEBUG_GPIO_INFO
        kconfig-tweak --enable CONFIG_DEBUG_SPI
        kconfig-tweak --enable CONFIG_DEBUG_SPI_ERROR
        kconfig-tweak --enable CONFIG_DEBUG_SPI_WARN
        kconfig-tweak --enable CONFIG_DEBUG_SPI_INFO

        kconfig-tweak --enable CONFIG_STACK_CANARIES

        kconfig-tweak --disable CONFIG_NSH_DISABLE_HELP
        kconfig-tweak --disable CONFIG_NSH_DISABLE_LS

        kconfig-tweak --enable CONFIG_BL602_SPI0

        kconfig-tweak --enable CONFIG_CLOCK_MONOTONIC
        kconfig-tweak --enable CONFIG_SIG_EVTHREAD
        kconfig-tweak --set-val CONFIG_SIG_SIGWORK 17
        kconfig-tweak --set-val CONFIG_PREALLOC_MQ_MSGS 4
        kconfig-tweak --set-val CONFIG_PREALLOC_MQ_IRQ_MSGS 4
        kconfig-tweak --set-val CONFIG_MQ_MAXMSGSIZE 32
        kconfig-tweak --enable CONFIG_SCHED_WORKQUEUE
        kconfig-tweak --enable CONFIG_SCHED_HPWORK
        kconfig-tweak --set-val CONFIG_SCHED_HPNTHREADS 1
        kconfig-tweak --set-val CONFIG_SCHED_HPWORKPRIORITY 224
        kconfig-tweak --set-val CONFIG_SCHED_HPWORKSTACKSIZE 2048

        kconfig-tweak --enable CONFIG_SCHED_BACKTRACE

        kconfig-tweak --enable CONFIG_DEV_URANDOM
        kconfig-tweak --enable CONFIG_DEV_URANDOM_RANDOM_POOL

        kconfig-tweak --enable CONFIG_SPI
        kconfig-tweak --enable CONFIG_SPI_EXCHANGE
        kconfig-tweak --enable CONFIG_SPI_DRIVER

        kconfig-tweak --enable CONFIG_DEV_GPIO
        kconfig-tweak --set-val CONFIG_DEV_GPIO_NSIGNALS 1

        kconfig-tweak --enable CONFIG_DRIVERS_RF
        kconfig-tweak --enable CONFIG_RF_SPI_TEST_DRIVER

        kconfig-tweak --enable CONFIG_CRYPTO
        kconfig-tweak --enable CONFIG_CRYPTO_BLAKE2S
        kconfig-tweak --enable CONFIG_CRYPTO_RANDOM_POOL
        kconfig-tweak --enable CONFIG_CRYPTO_RANDOM_POOL_COLLECT_IRQ_RANDOMNESS

        kconfig-tweak --set-str CONFIG_FS_MQUEUE_MPATH "/var/mqueue"
        kconfig-tweak --set-val CONFIG_FS_MQUEUE_NPOLLWAITERS 4

        kconfig-tweak --enable CONFIG_LIBC_FLOATINGPOINT

        kconfig-tweak --enable CONFIG_LIBSX1262
        kconfig-tweak --set-val CONFIG_LIBSX1262_PRECISION 0
        kconfig-tweak --enable CONFIG_LIBLORAWAN
        kconfig-tweak --enable CONFIG_LIBNPL
        kconfig-tweak --enable CONFIG_LIBTINYCBOR
        kconfig-tweak --enable CONFIG_LIBRUST
        kconfig-tweak --enable CONFIG_LIBBL602_ADC

        kconfig-tweak --enable CONFIG_EXAMPLES_BL602_ADC_TEST
        kconfig-tweak --set-str CONFIG_EXAMPLES_BL602_ADC_TEST_PROGNAME "bl602_adc_test"
        kconfig-tweak --set-val CONFIG_EXAMPLES_BL602_ADC_TEST_PRIORITY 100
        kconfig-tweak --set-val CONFIG_EXAMPLES_BL602_ADC_TEST_STACKSIZE 2048

        kconfig-tweak --enable CONFIG_EXAMPLES_GPIO
        kconfig-tweak --set-str CONFIG_EXAMPLES_GPIO_PROGNAME "gpio"
        kconfig-tweak --set-val CONFIG_EXAMPLES_GPIO_PRIORITY 100
        kconfig-tweak --set-val CONFIG_EXAMPLES_GPIO_STACKSIZE 2048

        kconfig-tweak --enable CONFIG_EXAMPLES_LORAWAN_TEST
        kconfig-tweak --set-str CONFIG_EXAMPLES_LORAWAN_TEST_PROGNAME "lorawan_test"
        kconfig-tweak --set-val CONFIG_EXAMPLES_LORAWAN_TEST_PRIORITY 100
        kconfig-tweak --set-val CONFIG_EXAMPLES_LORAWAN_TEST_STACKSIZE 2048

        kconfig-tweak --enable CONFIG_EXAMPLES_SPI_TEST
        kconfig-tweak --set-str CONFIG_EXAMPLES_SPI_TEST_PROGNAME "spi_test"
        kconfig-tweak --set-val CONFIG_EXAMPLES_SPI_TEST_PRIORITY 100
        kconfig-tweak --set-val CONFIG_EXAMPLES_SPI_TEST_STACKSIZE 2048

        kconfig-tweak --enable CONFIG_EXAMPLES_SPI_TEST2
        kconfig-tweak --set-str CONFIG_EXAMPLES_SPI_TEST2_PROGNAME "spi_test2"
        kconfig-tweak --set-val CONFIG_EXAMPLES_SPI_TEST2_PRIORITY 100
        kconfig-tweak --set-val CONFIG_EXAMPLES_SPI_TEST2_STACKSIZE 2048

        kconfig-tweak --enable CONFIG_EXAMPLES_SX1262_TEST
        kconfig-tweak --set-str CONFIG_EXAMPLES_SX1262_TEST_PROGNAME "sx1262_test"
        kconfig-tweak --set-val CONFIG_EXAMPLES_SX1262_TEST_PRIORITY 100
        kconfig-tweak --set-val CONFIG_EXAMPLES_SX1262_TEST_STACKSIZE 2048

        kconfig-tweak --enable CONFIG_EXAMPLES_TINYCBOR_TEST
        kconfig-tweak --set-str CONFIG_EXAMPLES_TINYCBOR_TEST_PROGNAME "tinycbor_test"
        kconfig-tweak --set-val CONFIG_EXAMPLES_TINYCBOR_TEST_PRIORITY 100
        kconfig-tweak --set-val CONFIG_EXAMPLES_TINYCBOR_TEST_STACKSIZE 2048

        kconfig-tweak --enable CONFIG_INTERPRETERS_BAS
        kconfig-tweak --set-str CONFIG_INTERPRETER_BAS_VERSION "2.4"
        kconfig-tweak --set-val CONFIG_INTERPRETER_BAS_PRIORITY 100
        kconfig-tweak --set-val CONFIG_INTERPRETER_BAS_STACKSIZE 4096
        kconfig-tweak --enable CONFIG_INTERPRETER_BAS_VT100

        # Preserve the build config
        cp .config nutt.config

        # Run the build
        make

        # Dump the disassembly to nuttx.S
        riscv64-unknown-elf-objdump \
          -t -S --demangle --line-numbers --wide \
          nuttx \
          >nuttx.S \
          2>&1

    - name: Upload Build Outputs
      uses: actions/upload-artifact@v2
      with:
        name: nuttx.zip
        path: nuttx/nuttx/nuttx*

    - name: Zip Build Outputs
      run: |
        cd nuttx/nuttx
        zip nuttx.zip nuttx*

    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ steps.date.outputs.date }}
        release_name: release-${{ steps.date.outputs.date }}
        draft: true
        prerelease: false

    - name: Upload Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: nuttx/nuttx/nuttx.zip
        asset_name: nuttx.zip
        asset_content_type: application/zip

    - name: Publish Release
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        
